apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rmdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust storage size as per your requirements