apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rmdb-ss
spec:
  replicas: 1
  serviceName: rmdb-service
  selector:
    matchLabels:
      app: goalsapp-mongodb
  template:
    metadata:
      labels:
        app: goalsapp-mongodb
    spec:
      containers:
      # - name: goalsapp-mongodb
      - name: rm-db
      #  image: goalsapp.azurecr.io/mongo:latest
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: rmdb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: rmdb-data
    spec:
      storageClassName: standard
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi  # Should match the size specified in mongodb-pvc.yaml

