apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendence-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendence-frontend
  template:
    metadata:
      labels:
        app: attendence-frontend
    spec:
      containers:
      - name: attendence-frontend
        image: attendencefe:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: attendencefe-cm
