apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendence-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendence-backend
  template:
    metadata:
      labels:
        app: attendence-backend
    spec:
      containers:
     # - name: goals-backend
     #   image: goalsapp.azurecr.io/goals-backend:latest
      - name: attendence-backend
        image: abe:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: attendencebe-cm
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: attendencebe-cm
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_DB

              
