apiVersion: v1
kind: ConfigMap
metadata:
  name: rmfe-cm
data:
  nginx.conf: |
    events {}

    http {
      include mime.types;

        server {
            listen 80;
            
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
                try_files $uri $uri/ /index.html;
              }

            location /goals {
                # Forward requests to the backend service using environment variables
                proxy_pass  http://rmbe-svc:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
              }
    }