apiVersion: apps/v1
kind: Deployment
metadata:
  name: rm-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rm-frontend
  template:
    metadata:
      labels:
        app: rm-frontend
    spec:
      containers:
      - name: rm-frontend
        image: rmfrontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: rmfe-cm
